name: GitHub Actions Demo
run-name: ${{ github.actor }} Mencoba GitHub Actions
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"