name: GitHub Actions Demo
run-name: ${{ github.actor }} Mencoba GitHub Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
            php-version: '8.1'
      - name: composer manifest package validation
        run: composer validate --strict
      - name: install composer dependencies
        run: composer install
      - name: testing one test
        run: ./vendor/bin/phpunit --group testGuzzle